<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationIcon>Assets\kerphone.ico</ApplicationIcon>
    <AssemblyName>KerPhone</AssemblyName>
    <RootNamespace>SoftPhone</RootNamespace>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesToSingleFile>true</IncludeNativeLibrariesToSingleFile>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
    <AssemblyTitle>KerPhone</AssemblyTitle>
    <Product>KerPhone</Product>
    <Description>Softphone SIP - Association KerBzh</Description>
    <Company>Association KerBzh</Company>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="pjsip_wrapper.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <Resource Include="Assets\kerphone_logo.png" />
    <Resource Include="Assets\kerphone.ico" />
  </ItemGroup>

</Project>
